version: '4.36.0'
services:
  db:
    image: mysql
    container_name: modaBack-end
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3311
    ports:
      - "3311:3311"
    volumes:
      - Moda_data:/var/lib/mysql

volumes:
  Moda_data: