server:
    error:
        include-stacktrace: on_param


spring:
    datasource:
        url: jdbc:mysql://localhost:3310/toNaModaBack?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
