server:
    error:
        include-stacktrace: never  # Melhor para produção

spring:
    datasource:
        url: jdbc:mysql://localhost:3310/toNaModaBack?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: validate  # Melhor para produção, evita alterações no banco de dados

